# Generated by Django 6.0.5 on 2026-05-19 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_user_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='threat',
            name='url',
        ),
        migrations.AddField(
            model_name='alert',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='parent_alerts', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='status',
            field=models.CharField(choices=[('safe', 'Safe'), ('suspicious', 'Suspicious'), ('dangerous', 'Dangerous')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='url',
            field=models.URLField(db_index=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='blockrule',
            name='domain',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='blockrule',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='blockrule',
            name='keyword',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='last_active',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('secure', 'Secure'), ('risk', 'At Risk')], db_index=True, default='secure', max_length=10),
        ),
        migrations.AlterField(
            model_name='threat',
            name='detected_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='threat',
            name='risk_score',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='threat',
            name='threat_type',
            field=models.CharField(choices=[('phishing', 'Phishing'), ('malware', 'Malware'), ('adult', 'Adult Content')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('parent', 'Parent'), ('child', 'Child')], db_index=True, default='parent', max_length=10),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', 'timestamp'], name='app_activit_user_id_63ddab_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', 'status'], name='app_activit_user_id_10aa40_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['timestamp', 'status'], name='app_activit_timesta_45c1cf_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['user', 'is_read'], name='app_alert_user_id_50a006_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['user', 'created_at'], name='app_alert_user_id_a1797e_idx'),
        ),
        migrations.AddIndex(
            model_name='blockrule',
            index=models.Index(fields=['user', 'is_active'], name='app_blockru_user_id_165e07_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['user', 'status'], name='app_device_user_id_b44f96_idx'),
        ),
        migrations.AddIndex(
            model_name='threat',
            index=models.Index(fields=['threat_type', 'risk_score'], name='app_threat_threat__becb40_idx'),
        ),
    ]
